# Generated by Django 5.0.6 on 2024-06-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicuser',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='clinicuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
